# Generated by Django 3.1.1 on 2020-09-24 06:54

import customers.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import genMerch.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('middle_name', genMerch.fields.TitleCaseCharfield(blank=True, max_length=40, null=True)),
                ('last_name', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', genMerch.fields.PhoneNumberField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=11), customers.validators.validate_phone_number])),
                ('profile_pic', models.ImageField(upload_to='images/customers/profile-pics/')),
                ('city', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('province', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('zip_code', models.PositiveIntegerField()),
                ('country', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widow/er'), ('D', 'Divorced')], default='S', max_length=1)),
                ('spouse_name', genMerch.fields.TitleCaseCharfield(blank=True, max_length=250, null=True)),
                ('spouse_occupation', genMerch.fields.TitleCaseCharfield(blank=True, max_length=40, null=True)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('father_name', genMerch.fields.TitleCaseCharfield(max_length=250)),
                ('father_occupation', genMerch.fields.TitleCaseCharfield(blank=True, max_length=40, null=True)),
                ('mother_name', genMerch.fields.TitleCaseCharfield(max_length=250)),
                ('mother_occupation', genMerch.fields.TitleCaseCharfield(blank=True, max_length=40, null=True)),
                ('height', models.FloatField(verbose_name='Height (cm)')),
                ('weight', models.FloatField(verbose_name='weight (kg)')),
                ('religion', genMerch.fields.TitleCaseCharfield(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customers.person')),
                ('date_registered', models.DateField(default=datetime.date.today)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('employee_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('customers.person',),
        ),
    ]
