# Generated by Django 3.1.1 on 2020-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(
                choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
