# Generated by Django 3.1.1 on 2020-09-14 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200914_1312'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
