# Generated by Django 3.1.1 on 2020-09-24 05:27

import customers.validators
import django.core.validators
from django.db import migrations
import genMerch.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200924_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=genMerch.fields.PhoneNumberField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(limit_value=11), customers.validators.validate_phone_number]),
        ),
    ]
