# Generated by Django 3.1.1 on 2020-09-24 00:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
import genMerch.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(default=datetime.date.today)),
                ('sku', models.PositiveIntegerField(default=0)),
                ('category', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('prod_name', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('brand', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('color', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('stocks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/products/prod_image/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
            options={
                'db_table': 'Product_Image',
            },
        ),
    ]
