# Generated by Django 3.1.1 on 2020-09-14 21:49

import datetime
from django.db import migrations, models
import genMerch.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(default=datetime.date.today)),
                ('prod_name', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('category', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('brand', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('color', genMerch.fields.TitleCaseCharfield(max_length=40)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('stocks', models.IntegerField()),
                ('image1', models.ImageField(upload_to='static/images/products/prod_image/')),
                ('image2', models.ImageField(upload_to='static/images/products/prod_image/')),
                ('image3', models.ImageField(upload_to='static/images/products/prod_image/')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
