# Generated by Django 3.1.1 on 2020-10-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
