# Generated by Django 3.1.1 on 2020-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
